feat: added new landing page with separate sections and guidelines.
akash-network/console-old pull request #145
Opened 2023-07-17 20:10 UTC by ArthurEmma2

This PR replaces the default route /new-deployment with a customizable landing page at /landing. The landing page's content is now driven by a metadata. 

This PR solves #100

2023-07-17 20:36 UTC, ArthurEmma2 commented
@jtary check this out

2023-07-20 17:51 UTC, jtary commented on web/src/pages/CustomApp.tsx
> -      // or it could also happen that user didn't change anything and error is "Query failed with (6): rpc error: code..."
Why did you remove these todos?

2023-07-20 17:54 UTC, jtary commented on web/src/pages/Landing.tsx
> +    <div className="tile_card_top-wrapper" style={{ marginTop: '-50px' }}>
This should be using the MUI components: (`Box`, `Flex`, etc.) instead of the native HTML components.

For the things like `marginTop`, use the props for Box (`mt`) instead of the style or sx props.

2023-07-20 17:56 UTC, jtary commented on web/src/pages/ReDeploy.tsx
> +    mxCreateDeployment({ sdl }); // Trigger the deployment mutation
There should be some sort of start/ending effects here to indicate to the user something is happening.

2023-07-20 18:02 UTC, jtary commented on web/src/style/TileCard.css
The general convention is to avoid using CSS files. For styling components, the order of preference is:

1. Use the native MUI props inside the JSX for the component
2. Use tailwind-css classes
3. Using styled to add custom CSS in the component file

I know the repo is pretty inconsistent with this right now, but that is the direction we are moving towards.

2023-07-20 18:07 UTC, jtary requested changes
For the new components for the landing page, please move the styling out of the CSS file and into the components themselves using the MUI native props. For handling the responsive styles, in MUI you can pass arrays of values to the props which represent different scales:

`marginTop={[2, 4, 6]}` -> this means the top margin will be size(2), size(4) or size(6) depending on the screen size based on the globally defined breakpoints.

2023-07-21 12:10 UTC, ArthurEmma2 commented on web/src/pages/ReDeploy.tsx
> +    mxCreateDeployment({ sdl }); // Trigger the deployment mutation
Do you have any idea how I can implement this  any example ?

2023-07-21 12:25 UTC, ArthurEmma2 commented on web/src/pages/ReDeploy.tsx
> +    mxCreateDeployment({ sdl }); // Trigger the deployment mutation
> There should be some sort of start/ending effects here to indicate to the user something is happening.

`  const handleSave = (sdl: SDLSpec) => {
    mxCreateDeployment({ sdl });
    setCardMessage('Saving SDL'); // Trigger the deployment mutation
  };

`

2023-07-22 21:29 UTC, jtary approved these changes

2023-07-22 21:32 UTC, merged